import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Sidebar from "@/layout/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex h-screen`}>
          <aside className="text-white w-64 border-r border-borderBG py-4">
            <Sidebar />
          </aside>
          <main className="flex-1 ">{children}</main>
      </body>
    </html>
  );
}
